/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Karyawan;

import Koneksi.ClassKoneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class GantiSandi extends javax.swing.JFrame {

    /**
     * Creates new form GantiSandi
     */
    public GantiSandi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JTextField();
        pwbaru = new javax.swing.JTextField();
        pwkonfirm = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setBackground(new java.awt.Color(153, 163, 239));
        user.setFont(new java.awt.Font("Century Gothic", 0, 34)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setBorder(null);
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 268, 700, 60));

        pwbaru.setBackground(new java.awt.Color(153, 163, 239));
        pwbaru.setFont(new java.awt.Font("Century Gothic", 0, 35)); // NOI18N
        pwbaru.setForeground(new java.awt.Color(255, 255, 255));
        pwbaru.setBorder(null);
        pwbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwbaruActionPerformed(evt);
            }
        });
        getContentPane().add(pwbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 700, 60));

        pwkonfirm.setBackground(new java.awt.Color(153, 163, 239));
        pwkonfirm.setFont(new java.awt.Font("Century Gothic", 0, 35)); // NOI18N
        pwkonfirm.setForeground(new java.awt.Color(255, 255, 255));
        pwkonfirm.setBorder(null);
        pwkonfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwkonfirmActionPerformed(evt);
            }
        });
        getContentPane().add(pwkonfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 543, 700, 60));

        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 660, 140, 40));

        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 660, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reset password.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void pwbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwbaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwbaruActionPerformed

    private void pwkonfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwkonfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwkonfirmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login lgn = null;
        try {
            lgn = new Login();
        } catch (SQLException ex) {
            Logger.getLogger(GantiSandi.class.getName()).log(Level.SEVERE, null, ex);
        }
        lgn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// Get text from fields
    String username = user.getText();
    String password = pwbaru.getText();
    String passbaru = pwkonfirm.getText();

if (!password.equals(passbaru)) {
    JOptionPane.showMessageDialog(null, "Password tidak sesuai", "gagal", JOptionPane.ERROR_MESSAGE);
} else {
    try {
        Connection c = ClassKoneksi.GetConnection();
        
        // Cek username
        String sql = "SELECT * FROM akun WHERE username = '" + username + "'";
        Statement s = c.createStatement();
        ResultSet r = s.executeQuery(sql);
        
        if (r.next()) {
            // Perbaikan query update - hilangkan spasi setelah MD5
            String updatesql = "UPDATE akun SET password = '" + password + "' WHERE username = '" + username + "'";
            Statement updateP = c.createStatement();
            updateP.executeUpdate(updatesql);
            
            JOptionPane.showMessageDialog(null, "Password berhasil diubah", "berhasil", JOptionPane.INFORMATION_MESSAGE);
            user.setText("");
            pwbaru.setText("");
            pwkonfirm.setText("");
            
            new Login().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Username tidak ditemukan", "gagal", JOptionPane.ERROR_MESSAGE);
        }
        
        // Tutup koneksi
        r.close();
        s.close();
        c.close();
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "gagal", JOptionPane.ERROR_MESSAGE);
    }
}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GantiSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GantiSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GantiSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GantiSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GantiSandi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField pwbaru;
    private javax.swing.JTextField pwkonfirm;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
